server:
  port: ${SERVER_PORT}

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: ${DB_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update